apiVersion: v1
kind: Pod
metadata:
  name: gds-avatar-jupyter
spec:
  containers:
  - name: pytorch
    image: centaurusinfra/torch-dali-jupyter:latest
    env:
    - name: CUDA_VISIBLE_DEVICES
      value: "6,7"
    - name: PFLOG
      value: /log/pflog    
    - name: LD_PRELOAD
      value: /lib/interpose/libpfinterpose.so    
    # command: ["sh", "-c", "sleep infinity"]
    command: ["sh", "-c", "jupyter lab --no-browser --allow-root --ip=0.0.0.0"]
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /nfs_3/data/cityscapes/
      name: dataset 
    - mountPath: /lib/interpose/
      name: intercept       
    - mountPath: /workspace/test
      name: test       
    - mountPath: /root/data
      name: data 
    - mountPath: /avatar
      name: avatar
    - name: pflog
      mountPath: /log/pflog      
  volumes:
  - name: dshm  # this is to trick pytorch when large size of shared memory is needed
    emptyDir:
      medium: Memory
  - name: dataset
    hostPath:
      path: /nfs_3/data/cityscapes/
      type: Directory
  - name: intercept
    hostPath:
      path: /home/steven/dev/alnair/alnair-profiler/profiler-hook-lib/build/lib
      type: Directory
  - name: test
    hostPath:
      path: /home/steven/dev/DataLoaders_DALI/
      type: Directory      
  - name: avatar
    hostPath:
      path: /mnt/gds/alnair/use-case
      type: Directory      
  - name: data
    hostPath:
      path: /mnt/gds-data
      type: Directory      
  - name: data1
    hostPath:
      path: /mnt/data
      type: Directory      
  - name: pflog
    hostPath:
      path: /var/lib/alnair/workspace/         
  restartPolicy: OnFailure